# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('recipient', models.TextField()),
                ('from_address', models.TextField()),
                ('successful', models.BooleanField(default=False)),
                ('error', models.TextField()),
                ('traceback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
