# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_auto_20161208_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('city',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
