# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_auto_20161209_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='traceback',
            field=models.TextField(null=True),
        ),
    ]
