# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0008_auto_20161209_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='body',
            new_name='html',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
