# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0009_auto_20161209_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
